spring:
  application:
    name: Movie-Rating-Consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: myGroup
  datasource:
    url: jdbc:postgresql://localhost:5432/movies
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081